import type { Teacher, Department, PaymentMethod, PaymentRecord } from "@/lib/types"

export const mockTeachers: Teacher[] = [
  {
    id: "1",
    firstName: "Sarah",
    lastName: "Johnson",
    email: "sarah.johnson@school.edu",
    phone: "+1 (555) 123-4567",
    department: "Mathematics",
    subject: "Algebra & Calculus",
    employeeId: "EMP001",
    joinDate: "2020-08-15",
    status: "active",
    experience: 8,
    qualification: "M.Sc Mathematics",
    salary: 65000,
    lastPaymentDate: "2024-01-01",
    pendingPayment: 5416.67,
  },
  {
    id: "2",
    firstName: "Michael",
    lastName: "Chen",
    email: "michael.chen@school.edu",
    phone: "+1 (555) 234-5678",
    department: "Science",
    subject: "Physics & Chemistry",
    employeeId: "EMP002",
    joinDate: "2019-01-10",
    status: "active",
    experience: 12,
    qualification: "Ph.D Physics",
    salary: 72000,
    lastPaymentDate: "2024-01-01",
    pendingPayment: 6000.0,
  },
  {
    id: "3",
    firstName: "Emily",
    lastName: "Rodriguez",
    email: "emily.rodriguez@school.edu",
    phone: "+1 (555) 345-6789",
    department: "English",
    subject: "Literature & Writing",
    employeeId: "EMP003",
    joinDate: "2021-03-22",
    status: "on-leave",
    experience: 5,
    qualification: "M.A English Literature",
    salary: 58000,
    lastPaymentDate: "2023-12-01",
    pendingPayment: 0,
  },
  {
    id: "4",
    firstName: "David",
    lastName: "Thompson",
    email: "david.thompson@school.edu",
    phone: "+1 (555) 456-7890",
    department: "History",
    subject: "World History",
    employeeId: "EMP004",
    joinDate: "2018-09-05",
    status: "active",
    experience: 15,
    qualification: "M.A History",
    salary: 68000,
    lastPaymentDate: "2024-01-01",
    pendingPayment: 5666.67,
  },
]

export const mockDepartments: Department[] = [
  { id: "1", name: "Mathematics", head: "Dr. Sarah Johnson", teacherCount: 8 },
  { id: "2", name: "Science", head: "Dr. Michael Chen", teacherCount: 12 },
  { id: "3", name: "English", head: "Prof. Emily Rodriguez", teacherCount: 6 },
  { id: "4", name: "History", head: "Dr. David Thompson", teacherCount: 4 },
]

export const paymentMethods: PaymentMethod[] = [
  {
    id: "card",
    type: "card",
    name: "Credit/Debit Card",
    icon: "💳",
    description: "Visa, Mastercard, American Express",
  },
  {
    id: "bank-transfer",
    type: "bank-transfer",
    name: "Bank Transfer",
    icon: "🏦",
    description: "Direct bank transfer",
  },
  {
    id: "paypal",
    type: "paypal",
    name: "PayPal",
    icon: "🅿️",
    description: "Pay with your PayPal account",
  },
]

export const mockPaymentRecords: PaymentRecord[] = [
  {
    id: "PAY001",
    teacherId: "1",
    teacherName: "Sarah Johnson",
    amount: 5416.67,
    currency: "USD",
    paymentType: "salary",
    description: "Monthly salary - January 2024",
    date: "2024-01-01",
    status: "completed",
    transactionId: "TXN123456789",
    method: "Bank Transfer",
  },
  {
    id: "PAY002",
    teacherId: "2",
    teacherName: "Michael Chen",
    amount: 6000.0,
    currency: "USD",
    paymentType: "salary",
    description: "Monthly salary - January 2024",
    date: "2024-01-01",
    status: "completed",
    transactionId: "TXN123456790",
    method: "Bank Transfer",
  },
  {
    id: "PAY003",
    teacherId: "1",
    teacherName: "Sarah Johnson",
    amount: 500.0,
    currency: "USD",
    paymentType: "bonus",
    description: "Performance bonus - Q4 2023",
    date: "2023-12-15",
    status: "completed",
    transactionId: "TXN123456791",
    method: "Credit Card",
  },
]

export const countries = [
  { code: "US", name: "United States" },
  { code: "CA", name: "Canada" },
  { code: "GB", name: "United Kingdom" },
  { code: "AU", name: "Australia" },
  { code: "DE", name: "Germany" },
  { code: "FR", name: "France" },
  { code: "JP", name: "Japan" },
  { code: "IN", name: "India" },
]
